root - ERROR - Error - 000002 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000069 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000157 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000166 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000553 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000625 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000627 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000629 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000651 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 'NoneType' object has no attribute 'text' - reformat_date - find_year_loop
Traceback (most recent call last):
  File "daily_routine.py", line 231, in reformat_date
    text = soup.find('div', class_='zwfbtime').text
AttributeError: 'NoneType' object has no attribute 'text'
root - ERROR - Error - 000661 - 'NoneType' object is not subscriptable - run_by_date
Traceback (most recent call last):
  File "daily_routine.py", line 277, in run_by_date
    formated_df['Time'] = formated_df['Time'].apply(lambda row: dt.datetime.strptime(row, '%Y-%m-%d %H:%M'))
TypeError: 'NoneType' object is not subscriptable
root - ERROR - Error - 000703 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000783 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000786 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000876 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000961 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 000783 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 002007 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 002310 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 002475 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "daily_routine.py", line 113, in run
    driver.get(first_page)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/andrew/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

