root - ERROR - Error - 002304 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "C:\Users\andrew.li\Desktop\Projects\Lim\Project_2-Forum\daily_routine_win.py", line 131, in call_webdriver
    driver.get(first_page)
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

root - ERROR - Error - 002508 - Message: timeout
  (Session info: headless chrome=78.0.3904.97)
 - Stock.run
Traceback (most recent call last):
  File "C:\Users\andrew.li\Desktop\Projects\Lim\Project_2-Forum\daily_routine_win.py", line 131, in call_webdriver
    driver.get(first_page)
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\andrew.li\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=78.0.3904.97)

